[workspace]
members = [
  "packages/apps",
  "packages/core",
  "packages/clients",
  "packages/utils",
]

# `starknet_ibc` workspace definition of shared resources
[workspace.package]
edition = "2023_11"
cairo-version = "2.7.0"
authors = ["Informal Systems <hello@informal.systems>"]
description = "Collection of Cairo components and contracts that implement and integrate IBC protocol with Starknet"
repository = "https://github.com/informalsystems/ibc-starknet"
license = "Apache-2.0"
keywords = ["ethereum", "starknet", "ibc", "cairo", "contracts"]

[workspace.scripts]
test = "snforge test"

[workspace.dependencies]
starknet = "2.7.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.26.0" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.1" }
openzeppelin_utils = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.1" }

[workspace.dev-dependencies]
snforge_std.workspace = true

[workspace.tool.fmt]
sort-module-level-items = true

# `starknet_ibc` primary contracts
[package]
name = "starknet_ibc_contracts"
version = "0.1.0"
description = "A set of Cairo smart contracts that implement IBC on Starknet"
edition.workspace = true

[scripts]
test.workspace = true

[tool]
fmt.workspace = true

[dependencies]
openzeppelin_access = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.1" }
openzeppelin_token.workspace = true
openzeppelin_utils.workspace = true
starknet.workspace = true
starknet_ibc_apps = { path = "packages/apps" }
starknet_ibc_core = { path = "packages/core" }
starknet_ibc_clients = { path = "packages/clients" }
starknet_ibc_utils = { path = "packages/utils" }

[dev-dependencies]
openzeppelin_testing = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.1" }
snforge_std.workspace = true

[[target.starknet-contract]]
