[package]
name = "starknet_ibc_apps"
version = "0.1.0"
description = "<DESCRIPTION HERE>"
edition.workspace = true

[scripts]
test.workspace = true

[tool]
fmt.workspace = true

[dependencies]
openzeppelin_token.workspace = true
openzeppelin_utils.workspace = true
starknet.workspace = true
starknet_ibc_core = { path = "../core" }
starknet_ibc_utils = { path = "../utils" }

[dev-dependencies]
snforge_std.workspace = true
